# Generated by Django 5.0.2 on 2024-03-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='caso_part',
            field=models.BooleanField(default=False),
        ),
    ]
