# Generated by Django 5.0.2 on 2024-02-29 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('negocio', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=13)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('metodo_contacto', models.IntegerField(choices=[(0, 'Visita local'), (1, 'Whatsapp'), (2, 'Instagram'), (3, 'Facebook')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('seña', models.FloatField(blank=True, null=True)),
                ('saldo', models.FloatField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(0, 'Presupuesto'), (1, 'En proceso'), (2, 'Entregado'), (3, 'Cancelado')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seña', models.FloatField(blank=True, null=True)),
                ('saldo', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
    ]
