# Generated by Django 5.0.2 on 2024-03-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='pedido',
            name='presupueto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
