# Generated by Django 5.0.2 on 2024-03-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pedido_cantidad_pedido_presupueto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='presupueto',
            new_name='presupuesto',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='seña',
            new_name='senia',
        ),
    ]
