# Generated by Django 5.0.2 on 2024-03-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_presupueto_pedido_presupuesto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.TextField(choices=[(0, 'Sin seña'), (1, 'Señado'), (2, 'En proceso'), (3, 'Para retirar'), (4, 'Entregado'), (5, 'Pagado'), (6, 'Cancelado')], default='Sin seña', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
