# Generated by Django 5.0.2 on 2024-02-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_presupuesto_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
