# Generated by Django 5.0.2 on 2024-02-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pedido_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='id',
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='numero',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
