# Generated by Django 5.0.2 on 2024-02-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_producto_cantidad_producto_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descuento',
            new_name='desc_procentaje',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='total',
        ),
        migrations.AddField(
            model_name='producto',
            name='desc_plata',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
