# Generated by Django 5.0.2 on 2024-02-26 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_rename_descuento_producto_desc_procentaje_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='desc_procentaje',
            new_name='desc_porcentaje',
        ),
    ]
