# Generated by Django 5.0.2 on 2024-02-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_categoria_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
