# Generated by Django 5.0.2 on 2024-02-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
