# Generated by Django 5.0.2 on 2024-02-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_alter_categoria_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='productos',
        ),
    ]
