# Generated by Django 5.0.2 on 2024-02-27 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_remove_categoria_productos'),
        ('core', '0007_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='presupuesto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.presupuesto'),
        ),
    ]
