# Generated by Django 5.0.2 on 2024-02-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
