# Generated by Django 5.0.2 on 2024-02-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_calc_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc_presupuesto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
