# Generated by Django 5.0.2 on 2024-02-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_calc_presupuesto_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calc_presupuesto',
            old_name='descripcion',
            new_name='info_adic',
        ),
        migrations.AddField(
            model_name='calc_presupuesto',
            name='cliente',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
