# Generated by Django 5.0.2 on 2024-02-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_descripcion_calc_presupuesto_info_adic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calc_Presupuesto',
        ),
    ]
