# Generated by Django 5.0.2 on 2024-02-26 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_calc_presupuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seña', models.FloatField(blank=True, null=True)),
                ('saldo', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
    ]
